### ISSUE TITLE
Any way to have MIGX install 100% as a sub-package?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [Bruno17/MIGX#115]
Hey Bruno,

Love the package, and using it in my template http://flexibilitymodx.com

After having MIGX installed by the package (as a sub-package) all works and is fine exept for errors generated in the error log:

```
[2013-08-06 05:43:27] (ERROR @ /assets/components/migx/connector.php) Error 42S02 executing statement: 
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'instance_c1683_modx.modx_migx_configs' doesn't exist
)
```

I am aware that I need to do more steps to install MIGX (as seen here: http://rtfm.modx.com/display/ADDON/MIGX#MIGX-Step2%3ASetuptheMIGXConfiguratorCustomManagerPage%28CMP%29andPackageManager)

But becouse my package is for non tech persons, I need a way to have the package install do this step... Do you see any way of doing this?

**Comment by Bruno17** [comment]
I've used teleport to create packages, which install multiple packages at once
