### ISSUE TITLE
MIGX and Redactor

### ISSUE THREAD

**Issue by sonicpunk** [Bruno17/MIGX#142]
I have just created a MIGX input field using the migxredactor inputTVtype and one thing that does not work is when the user creates an internal link in the rte.  It does not search for the pagetitle of the resource.  The admin has to place a ID instead.  This is a UI inconsistency

**Comment by jpdevries** [comment]
JP DeVries here, Lead Developer of Redactor for MODX. We've had this issue reported as well. It looks like MIGX's implementation is missing the `modalCallback` we use to initialize typeahead in the modal windows.

@Mark-H and I will discuss whether or not we need to address anything in our codebase, but for now I'm thinking a PR to adds the below code to MIGX should solve the issue.

```js
redactorOptions.modalCallback = function() {
    $('.typeahead').each(function(){
        $(this).typeahead({
            name: 'resources-oss',
            prefetch: {
                url: '[[+assetsUrl]]connector.php?action=resources/prefetch',
                ttl: [[+prefetch_ttl]]
            },
            remote: {
                url: '[[+assetsUrl]]connector.php?action=resources/search&query=%TERM%',
                wildcard: '%TERM%'
            },
            template: [
                '<p class="resource-id">#{{id}}</p>',
                '<p class="resource-name">{{& pagetitle}}</p>',
                '<p class="resource-introtext">{{& introtext}}</p>'
            ].join(''),
            valueKey: 'id',
            limit: 15,
            engine: Hogan
        });
});
```

**Comment by Mark-H** [comment]
I wonder if we can't drop the editor-specific init in MIGX, and simply call MODx.loadRTE on the element instead. The downside of that is people might not be able of using e.g. tinymce for the regular content, and Redactor as part of a MIGX TV, but then at least we wont have to worry about version-specific discrepancies..

**Comment by jpdevries** [comment]
simpler sounds good to me, but if all we do is call `MODx.loadRTE` wouldn't we be back to square one with the typeahead still not being activated?

**Comment by Mark-H** [comment]
Looking at how we're defining MODx.loadRTE in editor.tpl, that uses the redactorOptions variable which contains the modalCallback that initialises the typeahead. https://github.com/modmore/Redactor/blob/develop/core/components/redactor/templates/editor.tpl#L78

Haven't tried it yet tho

**Comment by Mark-H** [comment]
This is also affecting the new syntax highlighting in Redactor 2.
