### ISSUE TITLE
Customize width of MIGX Tv grid in Manager

### ISSUE THREAD

**Issue by osabate** [Bruno17/MIGX#169]
Ideally this should be configurable from the MIGX Management.
Apparently I'm not the only one requesting for this feature: 
http://forums.modx.com/thread/86359/how-to-change-the-width-of-migx-tv-grid-in-manager

Thanks!

**Comment by Bruno17** [comment]
should be fixed with this one
https://github.com/Bruno17/MIGX/commit/4d4abbbb17bbbd3f7235be5e9ef42b182ddc90c9
