### ISSUE TITLE
 MIGX Export view, opening in new browser tab, not downloading as a CSV

### ISSUE THREAD

**Issue by qodo** [Bruno17/MIGX#190]
When trying to export to CSV form A MIGX CMP the page used to offer the file as a download but a recent update changes this so it opens inline instead. Discussion here:

http://forums.modx.com/thread/96428/migx-export-view-opening-in-new-browser-tab-not-downloading-as-a-csv

**Comment by Bruno17** [comment]
was just trying with 2.9.1 (Chrome and FF) and it did download the csv - file

**Comment by qodo** [comment]
Thanks Bruno

This issue seems to be with 2.9.0 I am using in Firefox and Chrome. Is there a new version (2.9.1) that fixes this?

Many thanks!

**Comment by Bruno17** [comment]
here is 2.9.1 and 2.9.2
https://github.com/Bruno17/MIGX/tree/master/packages
try 2.9.2

**Comment by qodo** [comment]
Hi Bruno,

2.9.2 fixes this, thanks! This isn't available in the package manager from modx.com? It would be good if this could be updated!

Thanks again for such a great extra!
