### ISSUE TITLE
cellEditor with renderChunk problem

### ISSUE THREAD

**Issue by yujj** [Bruno17/MIGX#193]
Hello, i'm try to use cellEditor (both textEditor and listboxEditor) simultaneously with renderer (renderChunk). When edit cell, textEditor show value of renderer result, but no field value, and save it to the field. listboxEditor (1==value1||2==value2) trying to save value (not a key) to field (or save zero.. not sure).

i.e. cant't use cellEditor and renderChunk simultaneously due to this issue.

**Comment by Bruno17** [comment]
could you post your exported MIGX - config?

**Comment by yujj** [comment]
http://pastebin.com/NLVT5T0B

**Comment by yujj** [comment]
Hello.
How can i use listboxEditor with item 1==value1||2==value2||3==value3, instead of  value1||value2||value3

Now it works, but showing  keys (i.e. 1,2 or 3). It's possible to show values instead?

**Comment by yujj** [comment]
found solution here http://forums.modx.com/thread/41006/migx---multiitemsgridtv-for-modx---revolution?page=2#dis-post-236825

Thanks
