### ISSUE TITLE
Using resource-specific mediasource and multifile-uploader with MIGX not working

### ISSUE THREAD

**Issue by shot131** [Bruno17/MIGX#198]
Multifile-uploader by tis tutorial https://rtfm.modx.com/extras/revo/migx/migx.tutorials/migx.use-resource-specific-mediasource-and-multifile-uploader not working. I found, what media-source id is hard coded in grid.config.inc.php, if change that id to correctly, then it's work perfectly.

**Comment by Gibbs** [comment]
Thanks for pointing that out shot131, was driving me crazy why my media source with id 3 was being used!
