### ISSUE TITLE
inputTVtype: radio option?

### ISSUE THREAD

**Issue by pixelchutes** [Bruno17/MIGX#214]
The `inputTVtype` feature is great! Not having to create a TV for advanced functionality is really nice.

Is there a way to support **radio** inputTVtype similar to how checkbox works today?

I tried `inputOptionValues` with `inputTVtype` = radio, but the MIGX window does not load. (The MIGX connector fails with a *500 Internal Server Error*)

![migx](https://cloud.githubusercontent.com/assets/352182/9837412/f1b54dfc-59fa-11e5-94fa-af5509ad1a25.jpg)

Looking through the MIGX source code, I can see there is no support for radio inputTVtype today (however, using `inputTV` w/ a MODX radio Template Varialbe does work)

**Comment by Bruno17** [comment]
you can find the names of all default - TV - input - types here:
https://github.com/modxcms/revolution/tree/2.x/core/model/modx/processors/element/tv/renders/mgr/input

so, this is "option" for radio options.

also, most of custom-TV-inputtypes should work.
Some do not out of the box.

**Comment by pixelchutes** [comment]
Very nice! Thanks Bruno.
