### ISSUE TITLE
Form tabs data being wiped after adding date field

### ISSUE THREAD

**Issue by hugopeek** [Bruno17/MIGX#217]
I'm using latest MIGX on 2.4.

When adding a few items under a form tab item, the input fields are showing in the MIGX TV, but as soon as I go back to MIGX config, the formtabs column will be reset to just the parent item.

After further testing, it seems that adding items with standard text input type are not being erased, but problems start as soon as you add a date field as input TV type.

This is the raw formtabs content that causes the issue:

```
[{"MIGX_id":1,"caption":"Reisinformatie","print_before_tabs":"0","fields":[{"MIGX_id":1,"field":"date_departure","caption":"Vertrekdatum","description":"","description_is_code":"0","inputTV":"","inputTVtype":"date","validation":"","configs":"","restrictive_condition":"","display":"","sourceFrom":"config","sources":"","inputOptionValues":"","default":"","useDefaultIfEmpty":"0","pos":1},{"MIGX_id":2,"field":"date_return","caption":"Retourdatum","description":"","description_is_code":"0","inputTV":"","inputTVtype":"date","validation":"","configs":"","restrictive_condition":"","display":"","sourceFrom":"config","sources":"","inputOptionValues":"","default":"","useDefaultIfEmpty":"0","pos":2},{"MIGX_id":3,"field":"slots_total","caption":"Totaal aantal plekken","description":"","description_is_code":"0","inputTV":"","inputTVtype":"","validation":"","configs":"","restrictive_condition":"","display":"","sourceFrom":"config","sources":"","inputOptionValues":"","default":"","useDefaultIfEmpty":"0","pos":3},{"MIGX_id":4,"field":"slots_available","caption":"Aantal beschikbare plekken","description":"","description_is_code":"0","inputTV":"","inputTVtype":"","validation":"","configs":"","restrictive_condition":"","display":"","sourceFrom":"config","sources":"","inputOptionValues":"","default":"","useDefaultIfEmpty":"0","pos":4}],"pos":1}]
```

Error log is showing this a few times, but don't know if it's related:

```
[2015-09-20 13:05:52] (ERROR @ /Users/Hugo/Localhost/singha/core/components/migx/configs/migxdbfilters.config.inc.php : 22) PHP warning: implode(): Invalid arguments passed
```

**Comment by hugopeek** [comment]
Are the form tabs items supposed to be added to the migx_formtab_fields by the way? I'm seeing the test fields I added there, but not the date fields..

**Comment by travisbotello** [comment]
Same here...

I am using two formtabs. Every time I add, modify or delete a field on formtab A, formtab B gets overwritten with the changes I made for formtab A...and the fields in formtab A are deleted. The error log shows

`/core/components/migx/configs/migxdbfilters.config.inc.php : 22) PHP warning: implode(): Invalid arguments passed`

**Comment by Bruno17** [comment]
this should fix it
https://github.com/Bruno17/MIGX/commit/299b6893aa7a8e10bd190fb90124ed9433aba1bc
