### ISSUE TITLE
MIGX TV is created too high. draggable titlebar + fullscreen + x button cut off by screen

### ISSUE THREAD

**Issue by donShakespeare** [Bruno17/MIGX#219]
In MIGX 2.9.5 and 2.9.6

Have MIGX TV with richtext (TinymceWrapper enabled)
Click Add Item, or Edit existing item, top of MIGX modal is cut off.

**Comment by Bruno17** [comment]
maybe you did move the modal to far up. 
MODX does remember the position of the modal.

**Comment by donShakespeare** [comment]
Wow, MODx remembers it by PHP session? 
Brand new browsers and still the same problem.

I don't recall moving the modal in DevT, strage!

**Comment by donShakespeare** [comment]
I guess you are right. I fixed it through dev tools.
