### ISSUE TITLE
"addNewItemAt":"top" not working in CMP workflow

### ISSUE THREAD

**Issue by travisbotello** [Bruno17/MIGX#221]
Hello,

the "addNewItemAt":"top" setting is not having any effect in CMP setup. The items are always added to the bottom of the list which is not very useful when dealing with a large number of items.

Any ideas?

Thanks in advance

**Comment by Bruno17** [comment]
addNewItemAt is only for MIGX - TVs

In MIGXdb, the items are sorted by id ASC by default, but you can change the sortorder (and sort-field) within MIGXdb - settings

**Comment by travisbotello** [comment]
Perfect. Thanks for clarification!
