### ISSUE TITLE
[SOLVED] Error when i try to access to MIGX via extras menu in the manager...

### ISSUE THREAD

**Issue by nfl069** [Bruno17/MIGX#222]
Hi !

When I try to access to MIGX via extras menu in the manager, i've got this error : 

Trying to get property of non-object in core/components/migx/model/migx/migx.class.php on line 883

Do you have any ideas, please ?

ModX : 2.4.1-pl
MIGX : 2.9.6-pl

**Comment by Engelbert** [comment]
I can confirm this on my installation too.

   MODX Revolution 2.4.1-pl (traditional)
   MIGX 2.9.6-pl
   PHP Version 5.6.14

If you need more info just tell me what o provide mate.
Thanks in advance :smile:

**Comment by Bruno17** [comment]
does this fix it?
https://github.com/Bruno17/MIGX/issues/222

**Comment by nfl069** [comment]
Hi Bruno17 !

I replaced the migx.class.php with the new file from migx's github (RAW copy/paste), but the problem isn't solved. I've got a new error message : 

Object of class modFileMediaSource_mysql could not be converted to string core/components/migx/model/migx/migx.class.php on line 1031

Hope this can help you ?

Thanks

ModX : 2.4.1-pl (traditional)
MIGX : 2.9.6-pl + patch #222
PHP : 5.6.6
MySQL : 5.5.44-0+deb7u1-log

**Comment by Bruno17** [comment]
Of course, it should return the id, not the object here.
try this:
https://github.com/Bruno17/MIGX/commit/22004b3d057d0a0c8d55c4f431f42b65883a404f

**Comment by nfl069** [comment]
I've tested it, and all seem OK !
No error.
Thank...
Best regards

**Comment by nfl069** [comment]
Do I mark this problem solved and close ?
