### ISSUE TITLE
[[+total]] cannot be successfully resolved to zero

### ISSUE THREAD

**Issue by jubbbird** [Bruno17/MIGX#233]
...because upon an empty set:

return ' ';

occurs before the placeholder is set. Perhaps there's a simpler way to test for an empty list, but my first plan has been to call getImageList with no template but with toPlaceholder set so nothing appears. Then I test against [[+total]], which doesn't work because the placeholder isn't set/reset and maintains its value from a previous iteration.

I've used:

if (empty($outputvalue)) {
  $modx->setPlaceholder($totalVar, 0);
  return '';
}

to resolve the issue in a duplicate snippet.

**Comment by Bruno17** [comment]
fixed https://github.com/Bruno17/MIGX/commit/0c882a55050687851f7128e3828637abefa539b4#diff-02f4fc20c3fb8a39c0a78fda75f1d1e2R160
