### ISSUE TITLE
Multiple 'where' attributes ignored if they're the same

### ISSUE THREAD

**Issue by jcdm** [Bruno17/MIGX#234]
I created a call to migxLoopCollection with a &where clause that looks like the following:
{"name:LIKE":"%para%","AND:name:LIKE":"%hills%","AND:name:LIKE":"%uniting%","AND:name:LIKE":"%church%"}

The issue is that this string is then converted from JSON to an object. This causes a problem because this isn't actually valid JSON. The 'AND:name:LIKE' key is used multiple times and that flattens out the criteria to ignore all but the last value with that key.

This is not an issue exclusive to MIGX, but I report it here because it affects migxLoopCollection.

**Comment by Bruno17** [comment]
this is not an issue with MIGX or migxLoopCollection.
This is, because an array can't have multiple same arraykeys.

Try to split it in multiple subarrays:
```
[{"name:LIKE":"%para%"},{"name:LIKE":"%hills%"},{"name:LIKE":"%uniting%"},{"name:LIKE":"%church%"}]
```
