### ISSUE TITLE
No alert window on failed validation

### ISSUE THREAD

**Issue by yoavisimo** [Bruno17/MIGX#237]
Hi,

Marked the validation required checkbox on a specific field, if i leave it empty the window stays open but no alert shows up.

**Comment by Bruno17** [comment]
should be fixed with this lines:

https://github.com/Bruno17/MIGX/commit/0ebceb1301e28efd65f440371bcca2539a0b9bd1#diff-caa6bb787d43ede7f1052ef0a1d9b0c3R128

**Comment by yoavisimo** [comment]
Works great!

Thanks,
Jo.

**Comment by Gibbs** [comment]
It looks like this has regressed as there is no failure listener in ```core/components/migx/templates/mgr/updatewindow.tpl```. Is this intentional?
