### ISSUE TITLE
MIGxDB CMP - Empty Trash shows cached (already deleted) entries

### ISSUE THREAD

**Issue by sebastian-marinescu** [Bruno17/MIGX#245]
Hi Bruno, 

in a CMP made with MIGxDB I have a list of objects which can also be deleted. 

When deleting it and looking into the trash-view, I see the deleted items. Emptying the trash doesn't seem to work, because after that I can still see the entries in the trash-view, but actually it deletes the entry, so no problem with the processor. 

But the T(h)rash-View isn't updated. Even when I reload the window, the already deleted entry persists. If I manually clear the cache and reload the cmp, then the trash is empty.

**Comment by Bruno17** [comment]
hmm... never have seen an issue like that, where you need to clear the cache to see changes in a CMP-grid.
Do you have some special db-caching?

**Comment by sebastian-marinescu** [comment]
Nothing _special_, but I have this setting activated: 

**cache_db**

And I can confirm that after deactivating it, the empty trash view updates immediately. Hm.

So do you think there is a solution to this with activated db-cache? Maybe the processor for listing could query the db after emptying the trash without caching? Or maybe after emptying the trash MIGx should clear the cache?

**Comment by Bruno17** [comment]
try to add this lines, to clear the cache in that processor

**Comment by sebastian-marinescu** [comment]
I was actually getting used to Thrash :laughing: 

I'll test it now and will let you know if it works :+1: 

But out of curiosity, why do you delete in all contexts? 
And also why all the other cache partitions?

**Comment by sebastian-marinescu** [comment]
@Bruno17 works like a charm :sunglasses: Thanks

**Comment by Bruno17** [comment]
uncached snippet-calls with that records might be used in every context.

**Comment by sebastian-marinescu** [comment]
Okay, I see. Thanks :)
