### ISSUE TITLE
Empty Form Tabs in MODX 2.4.4

### ISSUE THREAD

**Issue by jchirschy** [Bruno17/MIGX#256]
Hello,

Since the update in MODX 2.4.4, form tabs in MIGX TV are empty. Grids are ok.
Did I miss something ?
I'm using MIGX 2.9.6-pl

Thanks for your help.

**Comment by Bruno17** [comment]
hmm... haven't empty formtabs in 2.4.4
I'm on 2.10.0 (beta10), but I think that shouldn't matter

**Comment by jchirschy** [comment]
After some researches, the problem appeared when I used the fixed related to this issue #222 with that 22004b3. It was actually working fine in migx-2.9-6.
In migx-2.9.7-pl, I'm facing the same problem with MODX 2.4.4.

**Comment by jchirschy** [comment]
To be a little more precise, this what I'm facing :
- MODX 2.4.2 + migx-2.9-6 : formtabs ok, but extra not loading in the manager (#222)
- MODX 2.4.2 + migx-2-9-6 + 'patch' 22004b3 : formtabs empty, but extra loading successfully in the manager.
- MODX 2.4.4 + migx-2-9-7 : formtabs empty, but extra loading successfully in the manager.

Is there someone else who face this problem ?

**Comment by Linsizn** [comment]
Рello,
MODX 2.4.4, - I'm using MIGX 2.10.0(10)
Does not work!
![migx_2 10 b10 _error1](https://cloud.githubusercontent.com/assets/18603391/14724671/4aaa343a-0820-11e6-935a-f6d1dc4cff8e.gif)
![migx_2 10 b10 _error2](https://cloud.githubusercontent.com/assets/18603391/14724672/4aad882e-0820-11e6-9bef-c2c991be322e.gif)

**Comment by Bruno17** [comment]
In most cases, where I've seen empty formtabs, there was an error in the formtabs-json

**Comment by Bruno17** [comment]
an upgrade to 2.10.0 beta10 has fixed the issue for @jchirschy
