### ISSUE TITLE
MIGX on MODX 2.5.0

### ISSUE THREAD

**Issue by weitblick** [Bruno17/MIGX#258]
after update from MODX 2.4.0 on MODX 2.5.0 and MIGX 2.9.4 on MIGX 2.9.6 the following debug message is shown:
`Notice: Trying to get property of non-object in /opt/lampp/htdocs/core/components/migx/model/migx/migx.class.php on line 883`
As workaround I can switch off the debug mode, but I'm not sure, if migx on MODX 2.5.0 works stable.

**Comment by Bruno17** [comment]
this is known and should allready be fixed with the coming 2.10 - version.
Its only a Notice, so setting debug to 0 should be good for now.
