### ISSUE TITLE
Some MIGX parts are "untranslateable"

### ISSUE THREAD

**Issue by whitebyte** [Bruno17/MIGX#261]
Please take alook at screenshots:
![migx-translate1](https://cloud.githubusercontent.com/assets/7704186/15682888/eb79f980-2789-11e6-85f0-221c314e8491.png)
![migx-translate2](https://cloud.githubusercontent.com/assets/7704186/15682889/eb7be70e-2789-11e6-80e1-1c1dbcbc8d73.png)

There are no lexicon entries for marked parts of the grid, even in English lexicon. Is there any way to translate this parts?

**Comment by Bruno17** [comment]
This are parts of MODX and normally they are translated, when you change the manager-language
For example here:
https://github.com/modxcms/revolution/blob/2.x/core/lexicon/ru/default.inc.php#L188

**Comment by whitebyte** [comment]
My manager language is Russian and the rest of the manager except for abovementioned parts are properly translated. So I thin this is MIGX issue. I suggest that somewhere it fails to recognize manager laguage and falls back to `en`

**Comment by Bruno17** [comment]
On my installations this parts are allways translated according to the manager-language

**Comment by whitebyte** [comment]
This is correct if MIGXdb-Settings -> Load Grid is set to "by button". When set to "auto", some parts of the grid remain untranslated. Just double-checked on two different installations. MODX 2.5.0 traditional, MIGX 2.9.6-pl

**Comment by Bruno17** [comment]
Is this a TV or a CMP?
On a TV, you need to use by button, because some parts of MODX aren't fully loaded, before the grid gets rendered.
This was the reason, why I added the by button - option.

**Comment by whitebyte** [comment]
This is a TV. So this issue is "wontfix", I suppose? If so, are there any known workarounds? Defer MIGX load? Add som JS via plugin and emulate user's click on "Load Grid" button?

**Comment by Ruslan-Aleev** [comment]
There is a problem, I think @Bruno17 could have added these lines to the lexicons too.
