### ISSUE TITLE
Posibility to group migx configs in the backend

### ISSUE THREAD

**Issue by dimitrihilverda** [Bruno17/MIGX#289]
Would be nice if we could group configs in the backend, We have a lot of configs, sometimes more then 30, for page blocks, content blocks, sidebar blocks.

maybe that each group has its own tab?

**Comment by Bruno17** [comment]
would a group-filter also work?

**Comment by dimitrihilverda** [comment]
I think so, when the result would be a group of configs, that it would be ok.
