### ISSUE TITLE
MigxDB - visual bug on change tab.

### ISSUE THREAD

**Issue by FerX** [Bruno17/MIGX#299]
I created a menu item with 3 configurations:
`/?a=index&namespace=migx&configs=gomme||marche||settings`
When I step from 1st to 2nd no problem.
When step 3 and back to the 2nd overlap the contents.
![image](https://user-images.githubusercontent.com/4459841/29120816-50d673fc-7d0c-11e7-890f-3bb8a10fe5b9.png)

**Comment by Bruno17** [comment]
each config has a unique MIGX ID?

**Comment by FerX** [comment]
ok thanks. I solved by putting 3 different ids.
