### ISSUE TITLE
Fields inside nested migx not render mediasource base_path

### ISSUE THREAD

**Issue by joeke** [Bruno17/MIGX#301]
When using a migx inside a migx and using image fields inside the nested migx, the mediasource path is not correctly parsed. I think the problem lies in the getImageList snippet, somewhere around line 221. The $mediasource->prepareOutputUrl() function renders the mediasource path fine for the first level migx, but not for the nested migx image fields.

**Comment by pixelive** [comment]
+1

**Comment by joeke** [comment]
Fixed it by adding the tvname property to the nested getImageList call. Thanks for your help @Bruno17
