### ISSUE TITLE
Make MIGX compatible with UTF8mb4 

### ISSUE THREAD

**Issue by digitalpenguin** [Bruno17/MIGX#311]
Now that the MODX core has been made compatible with UTF8mb4, it would be great to also have MIGX made compatible.

I think the main issue is that varchar index fields need to be brought down to a maximum of 191 instead of the current 255.

**Comment by Bruno17** [comment]
should be solved with 188a6f1ecc9d8326ba97d828b8caa36479722fae

**Comment by digitalpenguin** [comment]
Fantastic! Thanks Bruno!
