### ISSUE TITLE
[MIGXdb] Can't edit Date TV

### ISSUE THREAD

**Issue by hugopeek** [Bruno17/MIGX#313]
All other fields save as expected when closing the modal, except for date fields. I tried it with both Input TV Type: 'date' and with a real date TV, but no difference. I also tried changing the field type to datetime in the database schema after reading about #82.

It seems the date is set once when adding a new item, but updating it is impossible:

![migx-datefield-save-issue](https://user-images.githubusercontent.com/5436121/40043651-ba248f84-5857-11e8-91a8-b89fccbb6227.gif)

Using MIGX 2.12.0, no errors in console, no errors in log.

**Comment by Bruno17** [comment]
if your fieldname is publishedon, the update - processor changes its value automatically, as soon, as you change the pubished - field.
If you want to set its value by yourself, you will need another field in the form (not in the db) called 
ow_publishedon with a value of 1
see
https://github.com/Bruno17/MIGX/blob/master/core/components/migx/processors/mgr/default/update.php#L313

**Comment by hugopeek** [comment]
Fantastic, thanks again Bruno! It worked in combination with 'Use Default if Empty' set to Yes.
