### ISSUE TITLE
Image thumbnail in grid displays inconsistency

### ISSUE THREAD

**Issue by BigBlockStudios** [Bruno17/MIGX#316]
I am having a very strange problem with image thumbs in a nested grid.  Sometimes they will display, other times not.   Using either the Upload Files or Load from media source - thy both work in the sense that they will upload the images correctly  and create a record in my database.  BUT it is not showing some thumbnails.  i.e.  this particular image: "FB_IMG_1502019735126.jpg"  always displays a thumb,  if I make a copy of it and rename it (FB_IMG_1502019735126_XXX.jpg)  it will not display a thumb. 

in the logs I get phpthumb errors. 

```
(ERROR @ /var/www/vhosts/domain.com/core/model/phpthumb/phpthumb.class.php : 1686) PHP warning: getimagesize(/var/www/vhosts/domain.com/dev.domain.com/FB_IMG_150201973512XXX.jpg): failed to open stream: No such file or directory

(ERROR @ /var/www/vhosts/domain.com/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /var/www/vhosts/domain.com/core/cache/phpthumb/dev.domain.com__srca1dcd6fc83866af5776e62cd0ce811c3_parfe75230c38c1dd77cfb659e43ae25583_dat0.jpeg

(ERROR @ /var/www/vhosts/domain.com/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
```

The actual path for that image should be: 

`/var/www/vhosts/domain.com/dev.domain.com/assets/projects/{id}/images/FB_IMG_150201973512XXX.jpg`

So no differences in the database record between FB_IMG_150201973512XXX.jpg & FB_IMG_150201973512.jpg  one will work and the other not (even though they are the same image!!) 
Most images I upload will not display a thumb,  but there are 3 or 4 more that behave exactly like this one. 

Any thoughts as to what is going on? 

(while we are at it, is there any way to swap/change an image from the thumb in the grid?)

**Comment by BigBlockStudios** [comment]
never found out why, but this just "started working"  no explanation?

**Comment by Bruno17** [comment]
can't reproduce this issue
