### ISSUE TITLE
[Question] How to bulk import "rows" using csv or json?

### ISSUE THREAD

**Issue by ronttonen** [Bruno17/MIGX#335]
I have a bunch of rows I need to add to several pages. Doing this all one by one would be very time consuming. Is there a way to create a csv or json file and import all the data in there into a migx table?

**Comment by jenswittmann** [comment]
Hello @Bruno17 , the MIGX Package is very helpful. It would be nice to better understand the CSV stuff. Exporting a view as CSV works great. Inside this Repository is a file called processors/mgr/default/importcsvmigx.php. Whats the magic behind to use it? (:

**Comment by Bruno17** [comment]
there is now CSV import/export functionality included

**Comment by jenswittmann** [comment]
Hello @Bruno17 , thank you for your work. Is there a documentation for this?
