### ISSUE TITLE
Migx 2.13.0 release

### ISSUE THREAD

**Issue by JANogueira** [Bruno17/MIGX#344]
Hi Bruno,

It has been some time since the release of 2.12.0 (February 2018 if not mistaken) and there are several commits with fixes and improvements since then.

Are you planning a new release in the near future?

Many thanks in advance.

**Comment by Mayanktaker** [comment]
I was going to ask the same question. Migx needs to be updated for 2019. There are many many issues and most of them are mentioned here already but no response from sir Bruno. 
Please release the most awaited version.

**Comment by JANogueira** [comment]
I believe that Bruno is a bit far from the project compared to other times, but still very active.
We all have more active periods and less active periods for the most various reasons.

Bruno has his own reasons for not updating the project release version just yet even though he's always doing a great job for the community on a very extensive way and not just Migx.

Let's hope that everything is well with him. Maybe it is just lack of time and patience :)

**Comment by Bruno17** [comment]
@Mayanktaker 
thats a freetime - project. If you need help for a specific issue, just ask. I will try to help, so far my free time allows.

**Comment by Bruno17** [comment]
finally could release a 2.13.0 (rc2 for now)
hopefully it gets aproved soon
