### ISSUE TITLE
Add the ability to set the title of the MIGX-window in MIGX-TV form

### ISSUE THREAD

**Issue by Ruslan-Aleev** [Bruno17/MIGX#349]
If you configure MIGX-TV in the tabs of the MIGX-TV form, then the title of the MIGX window will always be "MIGX".
But if you configure MIGX-TV in the form of the MIGX component itself, you can set any title for MIGX window.

**In my opinion, it would be useful to set the window title in the "Form Tabs" of the MIGX-TV form.**

![wnd](https://user-images.githubusercontent.com/12523676/69011575-8a12a700-0985-11ea-9940-2aadffd8ffaa.png)

**Comment by Bruno17** [comment]
I've created the MIGX configurator CMP for more advanced settings.
The TV panel should only be used for very simple setups.
But a PR would be welcomed, of course.
