### ISSUE TITLE
Fatal Error (Uncaught --> Smarty Compiler: Syntax error in template)

### ISSUE THREAD

**Issue by navtsi** [Bruno17/MIGX#357]
I suddenly get a fatal error message. Seams a problem with Smarty Template

Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:/…/www_03/public/ecoedit/templates/default/element/tv/renders/input/url.tpl" on line 42 ",listeners: {'keydown': {fn:MODx.fireResourceFormChange, scope:this}}" - Unexpected ": ", expected one of: "}" <-- thrown in /…/www_03/core/model/smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 42

**Comment by navtsi** [comment]
Seam to be a problem with the TV type URL. If I change to type of the helper TV to text it works.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/15279

**Comment by Bruno17** [comment]
was fixed with modxcms/revolution#15279
