### ISSUE TITLE
Can't edit MigxDB entries / create new ones when url template variable is part of migx or migxdb

### ISSUE THREAD

**Issue by Waivor** [Bruno17/MIGX#358]
When trying to edit an existing row/record or adding a new entry into a migxdb table (backend of modx) the editing window shows up but keeps displaying a "loading" animation.

(Modx 2.8.0-pl, MariaDB 10.4)

**Comment by Waivor** [comment]
Update: It seems that this problem is caused when a url-type input field ist part of migx oder migxdb.

**Comment by Bruno17** [comment]
#358 seems to be related

**Comment by Bruno17** [comment]
was fixed with modxcms/revolution#15279
