### ISSUE TITLE
php8 compatibility

### ISSUE THREAD

**Issue by catsmeatman** [Bruno17/MIGX#361]
After update to php8.

Deprecated: Required parameter $config follows optional parameter $resource_id in /core/components/migx/model/migx/migx.class.php:1677

Deprecated: Required parameter $criteria follows optional parameter $tvFilters in /core/components/migx/model/migx/migx.class.php:2110

**Comment by Lord64** [comment]
A similar problem. Moreover, there was no problem on the nightly build of modx-2.8.3 dev-20210524. After the update to 2.8.3-pl appeared again.

**Comment by BenceSzalai** [comment]
This is still an issue in MigX v3.0.0-alpha5.

**Comment by ant-tar** [comment]
Observes this, still is actual

>Required parameter $config follows optional parameter $resource_id in /core/components/migx/model/migx/migx.class.php on line 1763
Required parameter $criteria follows optional parameter $tvFilters in /core/components/migx/model/migx/migx.class.php on line 2199

**Comment by dmitriy71n** [comment]
MIGX 3.0.0-alpha5, MODX 3.0.3-pl
php v8.0, v8.1, v8.2

Deprecated: Required parameter $config follows optional parameter $resource_id in /sites/site.dev/core/components/migx/model/migx/migx.class.php on line 1763

Deprecated: Required parameter $criteria follows optional parameter $tvFilters in /sites/site.dev/core/components/migx/model/migx/migx.class.php on line 2199

**Comment by Bruno17** [comment]
this should have been fixed with 
d16c4797d9896906e2a176b94f917a34fef90ed2
and
39dc2f51d5a90d93727a40a911470cab45ed0bea

and allready be implemented since 3.0.0-beta1

**Comment by dmitriy71n** [comment]
Thank you.
I have an old package from the repository.

сб, 26 авг. 2023 г. в 10:39, Bruno17 ***@***.***>:
