### ISSUE TITLE
Possible this.RenderCrossTick problem

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [Bruno17/MIGX#363]
I couldn't get the MIGXdb.Manage Events-Resources tutorial to work. https://docs.modx.com/3.x/en/extras/migxdb/migxdb.tutorials/manage-events-resources-in-a-cmp-with-help-of-migxdb

I noticed an error in the browser console.

`Uncaught SyntaxError: Invalid or unexpected token ?a=index&namespace=migx&configs=events:711 `

The offending code:

`            renderImage = ''/assets/components/migx/style/images/cross.png'; `

It looks like there's an extra single quote at the beginning of the image string.

Once I removed the references to this.RenderCrossTick, the CMP worked fine.

MIGX: 2.13.0-rc1
MODX: 2.8.1

**Comment by travisbotello** [comment]
Confirmed. Just saw the same problem on all of our website.

![Bildschirmfoto 2021-03-08 um 12 02 50](https://user-images.githubusercontent.com/1157380/110313126-4e7e6f00-8006-11eb-8e76-211bc3361543.png)
