### ISSUE TITLE
migxResourceMediaPath Not Working after Upgrade to 2.13.0-rc1

### ISSUE THREAD

**Issue by crimsonpixel** [Bruno17/MIGX#364]
I have a site running on PHP 7.4 with MODX 2.8.1 using a CMP which utilises the migxResourceMediaPath  snippet for the source for image upload but it is not not going to the correct path.

I have rolled back to the previous version of MIGX but this does not appear to have fixed this issue.

I can provide backend access for you to view as I am unable to resolve this problem.

**Comment by Bruno17** [comment]
this might be the easiest way to find the source of your issue

**Comment by crimsonpixel** [comment]
Have sent details.

Also when I upgraded to 2.13.0 is did actually cause the CMP page to disappear hence why I rolled back.

**Comment by Bruno17** [comment]
this issues should be solved with the rc3 release.
Please use the upload Action Button now and the remove_migx_and_image context-menu to remove migx-items and the image
