### ISSUE TITLE
Copy migx tv row from one resource to another

### ISSUE THREAD

**Issue by Intaria** [Bruno17/MIGX#370]
Hello.
Is there a way to copy row in migx tv from one resource to another?

**Comment by Bruno17** [comment]
with 2.13.0 pl
https://github.com/Bruno17/MIGX/tree/master/_packages

with the MIGX Configurator CMP, you can now add a new contextmenu 'export_import_migxitem'
if you do so, dont forget to add also the default context-menues like 
edit_migx, duplicate_migx and remove_migx

Now you can hit that new context-menu - button and the item will be as a json-string in a textarea - field, which you can copy
Than on the other MIGX-TV first create an empty new item and click the same button to paste the exported json-string into the textarea.

**Comment by Intaria** [comment]
Wow! Thanks u a lot
