### ISSUE TITLE
Hidden Checkbox in Tabs

### ISSUE THREAD

**Issue by mishantrop** [Bruno17/MIGX#405]
MODX 3.0.2-pl

Tabs config:
```JSON
[
    {
        "caption": "Hello world",
        "fields": [
            {
                "caption": "Published",
                "field": "published",
                "dataIndex": "published",
                "inputTVtype": "checkbox"
            }
        ]
    }
]
```

Columns config:
```JSON
[
    {
        "header": "Published",
        "dataIndex": "published",
        "editor": "this.textEditor",
        "renderer": "this.renderClickCrossTick"
    }
]
```

## Actual result
<img width="414" alt="Снимок экрана 2023-01-14 в 22 57 45" src="https://user-images.githubusercontent.com/5341208/212494236-65778a07-849f-4354-ae32-75b43c246980.png">

<img width="345" alt="Снимок экрана 2023-01-14 в 22 57 58" src="https://user-images.githubusercontent.com/5341208/212494232-3fd75c30-4c3d-40e9-a16d-d40cc91e6c49.png">

## Expected result
<img width="387" alt="Снимок экрана 2023-01-14 в 22 59 25" src="https://user-images.githubusercontent.com/5341208/212494265-eabb5bff-2c06-453f-991c-3f88daad6e88.png">

## Why checkbox is hidden:
Because of `opacity: 0` and possibly `position: absolute`.

<img width="588" alt="Снимок экрана 2023-01-14 в 22 58 43" src="https://user-images.githubusercontent.com/5341208/212494291-5d7e5b26-42f9-4b6e-a0ef-6b73de763ea5.png">

What if you comment out the extra styles:

<img width="582" alt="Снимок экрана 2023-01-14 в 22 59 21" src="https://user-images.githubusercontent.com/5341208/212494342-6042d64f-006d-4bc0-b4a6-630299d5c814.png">

<img width="387" alt="Снимок экрана 2023-01-14 в 22 59 25" src="https://user-images.githubusercontent.com/5341208/212494344-6e618bf1-f473-4b58-b671-93ec0e9c3cac.png">

**Comment by halftrainedharry** [comment]
I believe you have to specify the "Input Option Values" of the checkbox to get it displayed in the update window.

For example:

```
"inputOptionValues":"published==1"
```

**Comment by mishantrop** [comment]
@halftrainedharry  thank you and sorry for my inattention
