### ISSUE TITLE
MIGX-3.0.2-beta1 not create a table 'tasks' from mysql.schema.xml

### ISSUE THREAD

**Issue by oleang** [Bruno17/MIGX#415]
after i have click a "create Tables" for 'test package', i found that only  table "modx_test_tasklists" was created in database and show some error in the error log (see attached file). this is a bug?

MODX 2.8.6
MIGX 3.0.2

![capture_20231010094535542](https://github.com/Bruno17/MIGX/assets/142615/51971917-4f79-47a4-9812-e3f36181e17a)

![capture_20231010100029525](https://github.com/Bruno17/MIGX/assets/142615/ba91dc8d-63c8-40a9-9c55-c77f08d45971)

**Comment by Bruno17** [comment]
this should fix it:
https://github.com/Bruno17/MIGX/commit/9ba78088b34781056ecd6dfc2f84b6f335624672

**Comment by oleang** [comment]
> this should fix it: [9ba7808](https://github.com/Bruno17/MIGX/commit/9ba78088b34781056ecd6dfc2f84b6f335624672)

that worked, thanks Bruno.
