### ISSUE TITLE
MIGX 3.0.2 show warning "media_source_id" when use "this.renderChunk"

### ISSUE THREAD

**Issue by oleang** [Bruno17/MIGX#416]
I have created my Input/Show data form MIGXdb. I found that if i use "this.renderChunk" in columns, it will be have warning  about "media_source_id" every time of render (see attached) in error log. The columns display correct but how to avoid the warning. Need i define a "media_source_id" or not? 

MODX 3.0.4
MIGX 3.0.2
PHP 8.2.5

![01-column-show](https://github.com/Bruno17/MIGX/assets/142615/acafe55b-50ae-44ef-b26f-8dd01ebba76f)
![02-error-log](https://github.com/Bruno17/MIGX/assets/142615/2954db14-2801-44a6-a801-f7d83f3eee4f)
![03-column-setting](https://github.com/Bruno17/MIGX/assets/142615/dbf35196-8a87-40ec-96e2-fe4ded8a784f)
![04-render-chunk](https://github.com/Bruno17/MIGX/assets/142615/773d3c5c-5d06-4f24-993c-dac193bd1d39)

**Comment by halftrainedharry** [comment]
> Need i define a "media_source_id" or not?

This won't fix the warning.

To get rid of the warning, you have to change the code:
Change this line

https://github.com/Bruno17/MIGX/blob/9ba78088b34781056ecd6dfc2f84b6f335624672/core/components/migx/model/migx/migx.class.php#L1676

to this instead:
```
$properties['_media_source_id'] = isset($this->config['media_source_id']) ? $this->config['media_source_id'] : 0;
```

**Comment by oleang** [comment]
@halftrainedharry Thanks, That work.
