### ISSUE TITLE
Column buttons don't work on migx-3.0.2-beta1, MODX 3.0.4

### ISSUE THREAD

**Issue by lumikcz** [Bruno17/MIGX#425]
Hello Bruno17,
thanks for your amazing MIGX extra, which I've been using for years.

I found an issue with column buttons for updating, duplicating or removing items are not working on migx-3.0.2-beta1, MODX 3.0.4. These were working fine on MODX 2.x releases previously.

Context menu commands continue to work well.

![Screenshot 2024-03-11 at 23 30 24](https://github.com/Bruno17/MIGX/assets/1345993/3e93d0cb-7715-45a3-a018-fe6e31fba4be)

**These are the activated column buttons:**
![Screenshot 2024-03-11 at 23 30 49](https://github.com/Bruno17/MIGX/assets/1345993/1646fc84-5303-411b-8555-d9129022bd97)

I've tried to create fresh MIGX configuration and also to use one from another project running on MODX 2.x, but none of them work - the column buttons seem to be dead. 

There are no JavaScript errors in console, tried on Firefox, Safari and Chrome with same results.

**Comment by halftrainedharry** [comment]
This issue has the same cause as #424.

A "click" event on the MIGX-TV grid already gets handled by the click handler that was added for the new "Actions-Column" (marked green in your screenshot above).

---

To fix the issue yourself (without waiting for an update of the extra), you have to create a custom grid. Follow the instructions in this forum post:
https://community.modx.com/t/migxdb-cant-get-multiple-render-clickcrosstick-working/4217/7

**Comment by lumikcz** [comment]
Thanks a lot for your response and detailed explanation!

I'll try to go the custom-grid way you suggested. Specifically this thing is show-stopper for me, since I need to make easy-to-use GUI for the client, sticking jsut to context menu is no way.

Thanks!
