### ISSUE TITLE
assets path problem

### ISSUE THREAD

**Issue by Spica2** [Bruno17/MIGX#70]
I have a problem with the assets path is set to a custom name as suggestet in the chapter about hardening modx. The assets path migx is using is not set to the path set in the main config. So I run into problems with the CrossTickrenderer:
`renderImage = '/assets/components/migx/style/images/cross.png';`
I fixed this up manualy, but I assume, that this problem affects much more script passages.

**Comment by travisbotello** [comment]
Having the same problem. Using a custom assets path and the CrossTickRenderer icons are using hardcoded assets path. Any idea on how to fix this?
